---

# Crear directorio para el backup

- name: Crear directorio de copia de seguridad            
  file:                                
          path: "{{ backup_dir }}"       
          state: directory                                  
          mode: '0755'
                      
# Crear backup

- name: Crear copia de seguridad en CentOS
  mysql_db:                                
          name: "{{ database_name }}"           
          state: dump                                     
          target: "{{ centos_backup_file }}"
  when: ansible_distribution == 'CentOS'

- name: Crear copia de seguridad en Debian
  mysql_db:
          name: "{{ database_name }}"
          state: dump                     
          target: "{{ debian_backup_file }}"
  when: ansible_distribution == 'Debian'
          
# Copiar backup al control node

- name: Copiar backup al nodo de control en CentOS
  fetch:
          src: "{{ centos_backup_file }}"        
          dest: "/etc/ansible/recursos/backups/"                                  
          flat: yes
  when: ansible_distribution == 'CentOS'

- name: Copiar backup al nodo de control en Debian
  fetch:
          src: "{{ debian_backup_file }}"
          dest: "/etc/ansible/recursos/backups/"
          flat: yes
  when: ansible_distribution == 'Debian'
