---
- name: Instalar MariaDB
  hosts: 192.168.10.62
  become: true

  tasks:
          - name: Actualizar repositorios de paquetes
            dnf:
                    update_cache: yes

          - name: Instalar el paquete mariadb-server
            dnf:
                    name: mariadb-server
                    state: present

          - name: Instalar python
            yum:
                    name: python3
                    state: present

          - name: Instalar conector MySQL
            pip:
                    name: pymysql
                    state: present

          - name: Crear base de datos en MariaDB
            mysql_db:
                    name: bdwordpress
                    state: present

          - name: Crear usuario en MariaDB
            mysql_user:
                    name: wordpress
                    password: 1234
                    priv: "bdwordpress.*:ALL"
                    state: present
