---
- name: Instalaci贸n de apache y wordpress
  hosts: 192.168.10.61

  tasks:
          - name: Instalaci贸n del paquete de apache
            yum:
                    name: httpd
                    state: present

          - name: Iniciar httpd
            service:
                    name: httpd
                    state: started

          - name: Abrir puerto para el servicio http
            firewalld:
                    service: http
                    permanent: true
                    state: enabled

          - name: Restaurar servicio firewalld para guardar los cambios del firewall
            service:
                    name: firewalld
                    state: reloaded

          - name: Descargar WordPress
            get_url:
                    url: https://es.wordpress.org/latest-es_ES.tar.gz
                    dest: /tmp/wordpress.tar.gz
         
          - name: Comprobar si el directorio para wordpress existe
            stat:
                    path: "/var/www/html/wordpress"
            register: resultado

          - name: Crear directorio para Wordpress
            become: true
            file:
                    path: "/var/www/html/wordpress"
                    state: directory
                    owner: apache
                    group: apache
                    mode: "0755"
            when: not resultado.stat.exists


          - name: Extraer Wordpress
            unarchive:
                    src: /tmp/wordpress.tar.gz
                    dest: "/var/www/html"
                    remote_src: true

          - name: Copiar archivo de configuraci贸n
            copy:
                    src: "/etc/ansible/recursos/wp-config.php"
                    dest: "/var/www/html/wordpress"
                    owner: apache
                    group: apache

          - name: Cambiar permisos
            file:
                    path: "/var/www/html/wordpress"
                    state: directory
                    mode: "0755"
                    recurse: true

          - name: Reiniciar Apache
            systemd:
                    name: httpd
                    state: restarted

          - name: Instalar PHP y m贸dulos para WordPress
            become: true
            yum:
                    name: "{{ item }}"
                    state: present
            with_items:
                    - php
                    - php-mysqlnd
                    - php-gd
                    - php-xml
                    - php-mbstring
                    - php-json
                    - php-bcmath
                    - php-curl

          - name: reiniciar apache
            systemd:
                    name: httpd
                    state: restarted
