- name: Instalar Apache y PHP en CentOS 8
  hosts: 192.168.10.61
  become: yes

  tasks:
    - name: Actualizar paquetes
      dnf:
        update_cache: yes
        name: '*'
        state: latest

    - name: Instalar Apache
      dnf:
        name: httpd
        state: present

    - name: Abrir puerto para el servicio http
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Restaurar servicio firewalld para guardar los cambios del firewall
      service:
        name: firewalld
        state: reloaded

    - name: Iniciar y habilitar Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Instalar PHP
      dnf:
        name:
          - php
          - php-mysqlnd
          - php-opcache
          - php-gd
          - php-curl
          - php-mbstring
        state: present

    - name: Reiniciar Apache para cargar el módulo PHP
      systemd:
        name: httpd
        state: restarted

    - name: Descargar WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"
        mode: "0440"
        owner: "root"
        group: "root"

    - name: Extraer WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes
        mode: "0440"
        owner: "apache"
        group: "apache"

    - name: Configurar permisos de archivos y carpetas en WordPress
      file:
        path: "/var/www/html/wordpress"
        state: directory
        mode: "0755"
        owner: "apache"
        group: "apache"
        recurse: yes
        follow: yes

    - name: Copiar archivo de configuración de WordPress
      copy:
        src: "../recursos/wp-config.php"
        dest: "/var/www/html/wordpress/wp-config.php"
        mode: "0440"
        owner: "apache"
        group: "apache"

    - name: Configurar el archivo .htaccess
      copy:
        src: "../recursos/.htaccess"
        dest: "/var/www/html/wordpress/.htaccess"
        mode: "0440"
        owner: "apache"
        group: "apache"

